spring:
  application:
    name: tarifit-content-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/tarifittranslator}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: mongodb://localhost:27017/tarifittranslator_test

---
spring:
  config:
    activate:
      on-profile: integration
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/tarifittranslator_test}

server:
  port: ${SERVER_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.tarifit: DEBUG