spring:
  application:
    name: tarifit-content-service
  data:
    mongodb:
      uri: ${MONGODB_URI}

server:
  port: ${SERVER_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.tarifit: DEBUG